import { Typography, Box } from '@mui/material'
import Head from 'next/head'

export default function Home() {

  return (
    <div >
      <Head>
        <title>Home | Mohsen Mohseni</title>
        <meta name="description" content="Generated by mohsen mohseni" />
        <link rel="icon" href="/static/images/favicon-16x16.ico" />
      </Head>

      <Box component='main' sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh' }}>
        <Typography variant='colorizeText' sx={{ fontSize: '10vw', width: '80%'}} >Mohsen Mohseni</Typography>
      </Box>

      <footer></footer>
    </div>
  )
}
