import { Typography } from '@mui/material'
import Head from 'next/head'

export default function Home() {

  return (
    <div >
      <Head>
        <title>Home | Mohsen Mohseni</title>
        <meta name="description" content="Generated by mohsen mohseni" />
        <link rel="icon" href="/static/images/favicon-16x16.ico" />
      </Head>

      <main className='container'>
        <Typography variant='h1' className='homeTitle' >Mohsen Mohseni</Typography>
      </main>

      <footer></footer>
    </div>
  )
}
