import Head from 'next/head'

export default function Home() {

  return (
    <div >
      <Head>
        <title>Home | Mohsen Mohseni</title>
        <meta name="description" content="Generated by mohsen mohseni" />
        <link rel="icon" href="/static/images/favicon-16x16.ico" />
      </Head>

      <main>
        <h1>Mohsen Mohseni</h1>
      </main>

      <footer></footer>
    </div>
  )
}
